version: 2
defaults:
  working_directory: /tmp
jobs:
  zip:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - checkout
      - run:
          name: Make build directory for zipping 
          command: mkdir /tmp/workspace
      - run:
          name: Copy dist to the workspace directory
          command: cp -r Coffee-Shop /tmp/workspace/Coffee-Shop
      - run:
          name: Copy build scripts to workspace
          command: cp -r scripts /tmp/workspace/scripts
      - run:
          name: zip the folder
          command: zip -r Coffee-Shop.zip Coffee-Shop
      - run:
          name: list files
          command: ls /tmp/workspace/scripts/;ls /tmp/workspace/  
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - Coffee-Shop.zip
            - scripts
           
  deploy:
    docker:
      - image: google/cloud-sdk
        environment:
          STORAGE_BUCKET: dialog-flow-integration
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Initialize gcloud
          command: sh /tmp/workspace/scripts/authgcloud.sh
      - run:
          name: list files
          command: ls /tmp/workspace/
      - run:
          name: deploy
          command: /tmp/workspace/build/deploy.sh
workflows:
  version: 2
  build_deploy:
    jobs:
      - zip
      - deploy:
          requires:
            - zip
#          filters:
#            branches:
#              only: master