version: 2
defaults:
  working_directory: /tmp
jobs:
  zip:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - checkout
      - run:
          name: Make build directory for zipping 
          command: mkdir /tmp/workspace
      - run:
          name: Copy dist to the workspace directory
          command: cp -r Coffee-Shop /tmp/workspace/Coffee-Shop
      - run:
          name: Copy build scripts to workspace
          command: cp -r scripts /tmp/workspace/scripts
      - run:
          name: zip the folder
          command: |
           cd /tmp/workspace/
           zip -r Coffee-Shop.zip Coffee-Shop
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - .
         
  deploy:
    docker:
      - image: google/cloud-sdk
        environment:
          STORAGE_BUCKET: dialog-flow-rules
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Initialize gcloudls
          command: |
                  gcloud auth activate-service-account --key-file=/tmp/workspace/scripts/gcloud-service-key.json 
                  gcloud --quiet config set project ${GOOGLE_PROJECT_ID} 
      - run:
          name: Initialize gcloudls
          command: gsutil ls -b gs://$STORAGE_BUCKET || gsutil mb  gs://$STORAGE_BUCKET
      - run:
          name: upload to cloud storage
          command: gsutil cp  /tmp/workspace/Coffee-Shop.zip gs://$STORAGE_BUCKET
      - run:
          name: import in dialogflow
          command: gcloud alpha dialogflow agent import --source="gs://$STORAGE_BUCKET/Coffee-Shop.zip" 
workflows:
  version: 2
  build_deploy:
    jobs:
      - zip
      - deploy:
          requires:
           - zip
#          filters:
#            branches:
#              only: master
